#ifndef LDAA_PARAMS_H
#define LDAA_PARAMS_H

#define LDAA_M 24UL
#define LDAA_Q 8380417UL
#define LDAA_N 256UL
#define LDAA_S 6UL
#define LDAA_L 32UL
#define LDAA_C 8UL
#define LDAA_LOG_BETA 8UL
#define LDAA_LOG_W 1UL
#define LDAA_K_COMM 64UL
#define LDAA_ALPHA2 10UL

#define LDAA_COMMIT1_LENGTH (4UL + 4UL * (2UL * (1UL << LDAA_LOG_W) - 1UL) * \
        LDAA_LOG_BETA)
/*#define LDAA_COMMIT2_LENGTH ((2UL * (1UL << LDAA_LOG_W) - 1UL) * LDAA_LOG_BETA * \
        (LDAA_M * (2UL * LDAA_L + 3UL) + 1UL) + 2UL)
        */
#define LDAA_COMMIT2_LENGTH 900
#define LDAA_COMMIT3_LENGTH LDAA_COMMIT2_LENGTH

#define LDAA_SECRET_KEY_LENGTH (LDAA_M*LDAA_N) // Column of LDAA_N polynomials
#define LDAA_PUBLIC_KEY_LENGTH LDAA_N // polynomial
#define LDAA_ISSUER_BNTT_LENGTH (LDAA_COMMIT1_LENGTH * LDAA_K_COMM)
#define LDAA_ISSUER_BNTT2_LENGTH (LDAA_COMMIT2_LENGTH * LDAA_K_COMM)
#define LDAA_C1_LENGTH (LDAA_COMMIT1_LENGTH * LDAA_N * 4)
#define LDAA_C2_LENGTH (LDAA_COMMIT2_LENGTH * LDAA_N * 4)
#define LDAA_C3_LENGTH (LDAA_COMMIT3_LENGTH * LDAA_N * 4)

#endif
