#ifndef KYBER_PARAMS_H
#define KYBER_PARAMS_H

#define KYBER_SYMBYTES 32

#define KYBER_N 256
#define KYBER_Q 7681

#define KYBER_PUBLICKEYBYTES  736
#define KYBER_SECRETKEYBYTES  1632

#define KYBER_POLYBYTES              416
#define KYBER_POLYCOMPRESSEDBYTES    96

#define MAX_KYBER_K 4

#endif
