#ifndef NTTRU_PARAMS_H
#define NTTRU_PARAMS_H

#define NTTRU_SEEDBYTES 32
#define NTTRU_SHAREDKEYBYTES  32

#define NTTRU_N 768
#define NTTRU_Q 7681
#define NTTRU_LOGQ 13
#define NTTRU_ROOT_UNITY 20

#define NTTRU_COINBYTES (NTTRU_N/2)
#define NTTRU_MSGBYTES (NTTRU_N/4)
#define NTTRU_PUBLICKEYBYTES (NTTRU_LOGQ*NTTRU_N/8)
#define NTTRU_SECRETKEYBYTES (NTTRU_LOGQ*NTTRU_N/8 + NTTRU_PUBLICKEYBYTES)
#define NTTRU_CIPHERTEXTBYTES (NTTRU_LOGQ*NTTRU_N/8)

#endif
